
# Epub and Mobi
# =============

bookid: "VolumeOneBookId"

# BISAC Subject Headings List:
# http://www.bisg.org/what-we-do-0-136-bisac-subject-headings-list-major-subjects.php

subject: LIST / OF / SUBJECTS
source: http://www.source.org/

# MARC Code List for Relators:
# Editor [edt], Cover designer [cov], Translator [trl]
# http://www.loc.gov/marc/relators/relaterm.html

contributors:
  - edt: Lastname, Name
  - edt: Other Lastname, Name
  - cov: Lastname, Name
  - trl: Lastname, Name

